#!/bin/bash

PLAYER="playerctld"


FORMAT="{{ artist }}"

PLAYERCTL_STATUS=$(playerctl --player=$PLAYER status 2>/dev/null)

EXIT_CODE=$?

if [ $EXIT_CODE -eq 0 ]; then
    STATUS=$PLAYERCTL_STATUS
else
    STATUS="No Artist"
fi

if [ "$STATUS" = "Stopped" ]; then
    echo "No Artist"
    elif [ "$STATUS" = "Paused" ]; then
    playerctl --player=$PLAYER metadata --format "$FORMAT"
    elif [ "$STATUS" = "No Artist" ]; then
    echo "$STATUS"
else
    playerctl --player=$PLAYER metadata --format "$FORMAT"
fi
