#!/bin/bash

spotifyplayer() {
    LOCK_FILE_PLAYER="$HOME/.cache/eww-spotifyplayer.lock"
    EWW_BIN="$HOME/.local/bin/eww"

run() {
    ${EWW_BIN} open player -c ~/.config/eww/player/
}

# Open widgets
if [[ ! -f "$LOCK_FILE_PLAYER" ]]; then
    ${EWW_BIN} close player -c ~/.config/eww/player/
    touch "$LOCK_FILE_PLAYER"
    run && echo "ok good!"
elif [[ -f "$LOCK_FILE_PLAYER" ]]; then
    ${EWW_BIN} close player -c ~/.config/eww/player/
    rm "$LOCK_FILE_PLAYER" && echo "closed"
fi
}

spotifyplayer
