return {
  n = {
    ["<C-s>"] = "",
    ["<C-h>"] = "",
    ["<C-k>"] = "",
    ["<C-l>"] = "",
    ["<C-L>"] = "",
    ["<C-n>"] = "",
    ["<C-c>"] = "",
    ["<leader>wK"] = "",
    ["<leader>wk"] = "",
    ["<leader>wa"] = "",
    ["<leader>wl"] = "",
    ["<leader>wr"] = "",
    ["<leader>w"] = "",
    ["<leader>u"] = "",
    ["<leader>uu"] = "",
    ["<leader>D"] = "",
    ["<leader>t"] = "",
    ["<leader>th"] = "",
    ["<leader>tk"] = "",
    ["<leader>tt"] = "",
    ["<leader>b"] = "",
    ["<leader>g"] = "",
    ["<leader>h"] = "",
    ["<leader>v"] = "",
    ["<leader>rn"] = "",
    ["<leader>ra"] = "",
    ["<leader>gt"] = "",
    ["<leader>n"] = "",
    ["<Up>"] = "",
    ["<Down>"] = "",
  },
}
